import { ShortCodeEntry } from "./telecomTypes";

export const HARMONIZED_SHORT_CODES: ShortCodeEntry[] = [
  {
    id: "h-300",
    code: "300",
    displayCode: "300",
    protocol: "VOICE",
    service: "Call Centre / Help Desk",
    category: "support",
    description: "Harmonized short code to reach customer care across all mobile network operators in Nigeria.",
    howToUse: "Dial 300 from your phone.",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission (NCC)",
    sourceUrl: "https://www.ncc.gov.ng",
    lastVerified: "2025-03-01",
    isHarmonized: true,
    notes: "Free customer care line unified under NCC harmonized short code framework."
  },
  {
    id: "h-301",
    code: "301",
    displayCode: "301",
    protocol: "VOICE",
    service: "Voice Mail Deposit",
    category: "support",
    description: "Harmonized service code used to deposit a voice mail message for a recipient.",
    howToUse: "Dial 301 followed by the subscriber number or follow voice prompt instructions.",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission (NCC)",
    sourceUrl: "https://www.ncc.gov.ng",
    lastVerified: "2025-03-01",
    isHarmonized: true
  },
  {
    id: "h-302",
    code: "302",
    displayCode: "302",
    protocol: "VOICE",
    service: "Voice Mail Retrieval",
    category: "support",
    description: "Harmonized service code used to listen to and manage stored voice mail messages.",
    howToUse: "Dial 302 and follow your network's automated voice instructions.",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission (NCC)",
    sourceUrl: "https://www.ncc.gov.ng",
    lastVerified: "2025-03-01",
    isHarmonized: true
  },
  {
    id: "h-303",
    code: "303",
    displayCode: "*303#",
    protocol: "USSD",
    service: "Borrow Service",
    category: "borrow",
    description: "Harmonized short code to request airtime or data advance loans from your network.",
    howToUse: "Dial *303# and select airtime or data borrowing option from the menu.",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission (NCC)",
    sourceUrl: "https://www.ncc.gov.ng",
    lastVerified: "2025-03-01",
    isHarmonized: true
  },
  {
    id: "h-305",
    code: "305",
    displayCode: "*305#",
    protocol: "USSD",
    service: "STOP Service (VAS Management)",
    category: "vas",
    description: "Official NCC STOP Service short code to inspect, unsubscribe, or cancel unwanted Value Added Services (VAS) and subscriptions.",
    howToUse: "Dial *305# to view active paid services and select the STOP option.",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission (NCC Directive)",
    sourceUrl: "https://www.ncc.gov.ng",
    lastVerified: "2025-03-01",
    isHarmonized: true,
    notes: "Specifically designated by NCC as the STOP Service code for stopping unsolicited services."
  },
  {
    id: "h-310",
    code: "310",
    displayCode: "*310#",
    protocol: "USSD",
    service: "Check Balance",
    category: "balance",
    description: "Harmonized code to check main airtime balance across all Nigerian mobile networks.",
    howToUse: "Dial *310# to display your main credit balance on screen.",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission (NCC)",
    sourceUrl: "https://www.ncc.gov.ng",
    lastVerified: "2025-03-01",
    isHarmonized: true,
    notes: "Supersedes older legacy codes such as *556# (MTN) or *123# (Airtel)."
  },
  {
    id: "h-311",
    code: "311",
    displayCode: "*311*",
    protocol: "USSD",
    service: "Credit Recharge",
    category: "recharge",
    description: "Harmonized short code to load physical or electronic airtime recharge vouchers.",
    howToUse: "Dial *311*PIN# (e.g. *311*123456789012346#).",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission (NCC)",
    sourceUrl: "https://www.ncc.gov.ng",
    lastVerified: "2025-03-01",
    isHarmonized: true,
    notes: "Replaces legacy codes like *555* (MTN) or *126* (Airtel)."
  },
  {
    id: "h-312",
    code: "312",
    displayCode: "*312#",
    protocol: "USSD",
    service: "Data Plan Purchase",
    category: "data",
    description: "Harmonized portal to browse, select, and purchase mobile internet data bundles.",
    howToUse: "Dial *312# and navigate the interactive menu for daily, weekly, or monthly bundles.",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission (NCC)",
    sourceUrl: "https://www.ncc.gov.ng",
    lastVerified: "2025-03-01",
    isHarmonized: true,
    notes: "Replaces legacy codes like *131# (MTN) or *141# (Airtel)."
  },
  {
    id: "h-321",
    code: "321",
    displayCode: "*321#",
    protocol: "USSD",
    service: "Share Service",
    category: "recharge",
    description: "Harmonized short code to transfer airtime or gift data to another subscriber.",
    howToUse: "Dial *321# and choose whether to share airtime or transfer data.",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission (NCC)",
    sourceUrl: "https://www.ncc.gov.ng",
    lastVerified: "2025-03-01",
    isHarmonized: true
  },
  {
    id: "h-323",
    code: "323",
    displayCode: "*323#",
    protocol: "USSD",
    service: "Data Plan Balance",
    category: "data",
    description: "Harmonized USSD code to check remaining internet data bundle balance and validity.",
    howToUse: "Dial *323# to receive immediate on-screen data balance or SMS notification.",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission (NCC)",
    sourceUrl: "https://www.ncc.gov.ng",
    lastVerified: "2025-03-01",
    isHarmonized: true
  },
  {
    id: "h-2442",
    code: "2442",
    displayCode: "2442",
    protocol: "SMS",
    service: "Do-Not-Disturb (DND)",
    category: "dnd",
    description: "Official NCC short code to manage unsolicited promotional SMS and marketing calls.",
    howToUse: "Send SMS with text 'STOP' to 2442 for full DND, or 'ALLOW' to receive messages.",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission (NCC)",
    sourceUrl: "https://www.ncc.gov.ng/dnd",
    lastVerified: "2025-03-01",
    isHarmonized: true,
    notes: "Uses SMS protocol, not USSD dialing."
  },
  {
    id: "h-3232",
    code: "3232",
    displayCode: "3232",
    protocol: "SMS",
    service: "Mobile Number Portability (MNP)",
    category: "porting",
    description: "Harmonized short code used when switching mobile service providers while retaining your existing 11-digit phone number.",
    howToUse: "Send 'PORT' via SMS to 3232 after visiting the recipient operator customer service outlet with valid photo identification.",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission (NCC MNP Guidelines)",
    sourceUrl: "https://www.ncc.gov.ng",
    lastVerified: "2025-03-01",
    isHarmonized: true,
    notes: "Requires physical verification at the operator office per NCC regulatory compliance."
  },
  {
    id: "h-996",
    code: "996",
    displayCode: "*996#",
    protocol: "USSD",
    service: "SIM Registration & NIN-SIM Linkage",
    category: "nin",
    description: "Official harmonized portal for checking SIM registration status and linking National Identification Number (NIN) to SIM cards.",
    howToUse: "Dial *996# to check linked status or submit NIN verification request.",
    applicableNetworks: ["MTN", "Airtel", "Glo", "9mobile"],
    sourceName: "Nigerian Communications Commission / NIMC",
    sourceUrl: "https://www.ncc.gov.ng",
    lastVerified: "2025-03-01",
    isHarmonized: true,
    notes: "Replaces legacy codes like *785# (MTN) or *121*1# (Airtel)."
  }
];
