import { ProjectWithMedia } from "./types";
import { getLocalPublicUrl } from "./mediaManifest";

export const STATIC_PROJECTS: ProjectWithMedia[] = [
  {
    id: "7022dad7-1aa5-46a5-9100-793e6ec7cd66",
    slug: "aurora-commerce",
    title: "Aurora Commerce",
    client_name: "Retail Systems Exploration",
    project_type_label: "Concept Storefront",
    composition_variant: "featured",
    related_service_slug: "websites-web-applications",
    category: "E-Commerce",
    summary: "A high-performance digital commerce storefront concept exploring sub-100ms response targets.",
    description:
      "Aurora Commerce is an engineering design concept studying sub-100ms e-commerce interaction design, modular catalog management, and zero-layout-shift checkout flows.",
    problem: "How might a growing commerce brand make browsing and buying feel faster, clearer, and more resilient under heavy load?",
    solution:
      "A modular storefront concept with high-resolution product presentation, responsive layout layering, and pre-fetched catalog routing.",
    results: "Design and development concept focusing on sub-100ms interaction feedback and zero layout shift.",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Stripe API"],
    featured: true,
    live_url: null,
    github_url: null,
    year: 2026,
    sort_order: 1,
    media: [
      {
        id: "fdf00af5-d023-4aa4-8cf2-7b6808cd6172",
        project_id: "7022dad7-1aa5-46a5-9100-793e6ec7cd66",
        media_type: "image",
        title: "Hero View — Modern Retail Surface",
        url: getLocalPublicUrl("aurora-commerce", "hero.webp"),
        thumbnail_url: getLocalPublicUrl("aurora-commerce", "hero.webp"),
        provider: "Snow Media Library",
        alt_text: "Aurora Commerce storefront hero preview showing primary spatial layout concept",
        sort_order: 1,
      },
      {
        id: "6e415a9c-a042-48b2-a2fe-b0b0599251cf",
        project_id: "7022dad7-1aa5-46a5-9100-793e6ec7cd66",
        media_type: "image",
        title: "Desktop Surface — Catalog & Checkout",
        url: getLocalPublicUrl("aurora-commerce", "desktop.webp"),
        thumbnail_url: getLocalPublicUrl("aurora-commerce", "desktop.webp"),
        provider: "Snow Media Library",
        alt_text: "Aurora Commerce desktop catalog interface preview concept",
        sort_order: 2,
      },
      {
        id: "c900f06f-d596-4df1-a75b-94c035973fa1",
        project_id: "7022dad7-1aa5-46a5-9100-793e6ec7cd66",
        media_type: "image",
        title: "Mobile Surface — Responsive Navigation",
        url: getLocalPublicUrl("aurora-commerce", "mobile.webp"),
        thumbnail_url: getLocalPublicUrl("aurora-commerce", "mobile.webp"),
        provider: "Snow Media Library",
        alt_text: "Aurora Commerce mobile interface preview concept",
        sort_order: 3,
      },
    ],
  },
  {
    id: "02e05a53-4768-4326-b46b-d3c5ef219a3d",
    slug: "pulse-health",
    title: "Pulse Health",
    client_name: "Healthcare Systems Study",
    project_type_label: "Interface Study",
    composition_variant: "device-stack",
    related_service_slug: "custom-software-web-apps",
    category: "Web App",
    summary: "A calm appointment and customer portal concept for healthcare and service operations.",
    description:
      "Pulse Health is an interface study focusing on reducing administrative overhead for care providers via structured appointment scheduling and accessible patient portals.",
    problem: "How can a health portal reduce user friction around scheduling, medical record viewing, and account updates?",
    solution: "A clear booking flow concept with reactive state management, responsive scheduling UI, and high-contrast accessibility standards.",
    results: "Interface study exploring streamlined appointment workflows and accessible patient record interaction.",
    technologies: ["Next.js", "React", "TypeScript", "PostgreSQL", "Tailwind CSS"],
    featured: true,
    live_url: null,
    github_url: null,
    year: 2026,
    sort_order: 2,
    media: [
      {
        id: "5663d52c-7625-47fb-9943-965c22e4a84e",
        project_id: "02e05a53-4768-4326-b46b-d3c5ef219a3d",
        media_type: "image",
        title: "Hero View — Care Dashboard",
        url: getLocalPublicUrl("pulse-health", "hero.webp"),
        thumbnail_url: getLocalPublicUrl("pulse-health", "hero.webp"),
        provider: "Snow Media Library",
        alt_text: "Pulse Health portal hero preview concept",
        sort_order: 1,
      },
      {
        id: "5663d52c-7625-47fb-9943-965c22e4a84f",
        project_id: "02e05a53-4768-4326-b46b-d3c5ef219a3d",
        media_type: "image",
        title: "Desktop Surface — Scheduling Interface",
        url: getLocalPublicUrl("pulse-health", "desktop.webp"),
        thumbnail_url: getLocalPublicUrl("pulse-health", "desktop.webp"),
        provider: "Snow Media Library",
        alt_text: "Pulse Health desktop scheduling interface preview concept",
        sort_order: 2,
      },
      {
        id: "5663d52c-7625-47fb-9943-965c22e4a850",
        project_id: "02e05a53-4768-4326-b46b-d3c5ef219a3d",
        media_type: "image",
        title: "Mobile Surface — Patient Appointment View",
        url: getLocalPublicUrl("pulse-health", "mobile.webp"),
        thumbnail_url: getLocalPublicUrl("pulse-health", "mobile.webp"),
        provider: "Snow Media Library",
        alt_text: "Pulse Health mobile portal view concept",
        sort_order: 3,
      },
    ],
  },
  {
    id: "03f05a53-4768-4326-b46b-d3c5ef219a3e",
    slug: "orbit-finance",
    title: "Orbit Finance",
    client_name: "Fintech Interface Prototype",
    project_type_label: "Platform Prototype",
    composition_variant: "dark-lab",
    related_service_slug: "custom-software-web-apps",
    category: "Fintech",
    summary: "A fintech dashboard prototype exploring real-time telemetry display and ledger interface design.",
    description:
      "Orbit Finance is a platform prototype exploring streaming ledger UI patterns, interactive charting surfaces, and multi-currency portfolio views.",
    problem: "How can complex financial telemetry be rendered cleanly in browser environments without frame drops during rapid data updates?",
    solution: "WebGL charting components and state buffer concepts for market data visualization.",
    results: "Platform prototype demonstrating reactive charting UI and streaming ledger concepts.",
    technologies: ["React", "TypeScript", "Three.js", "WebSockets", "Tailwind CSS"],
    featured: true,
    live_url: null,
    github_url: null,
    year: 2026,
    sort_order: 3,
    media: [
      {
        id: "orb-hero-1",
        project_id: "03f05a53-4768-4326-b46b-d3c5ef219a3e",
        media_type: "image",
        title: "Hero View — Financial Telemetry Terminal",
        url: getLocalPublicUrl("orbit-finance", "hero.webp"),
        thumbnail_url: getLocalPublicUrl("orbit-finance", "hero.webp"),
        provider: "Snow Media Library",
        alt_text: "Orbit Finance financial terminal hero concept preview",
        sort_order: 1,
      },
      {
        id: "orb-desk-2",
        project_id: "03f05a53-4768-4326-b46b-d3c5ef219a3e",
        media_type: "image",
        title: "Desktop Surface — Real-Time Ledger View",
        url: getLocalPublicUrl("orbit-finance", "desktop.webp"),
        thumbnail_url: getLocalPublicUrl("orbit-finance", "desktop.webp"),
        provider: "Snow Media Library",
        alt_text: "Orbit Finance desktop dashboard concept screenshot",
        sort_order: 2,
      },
      {
        id: "orb-mob-3",
        project_id: "03f05a53-4768-4326-b46b-d3c5ef219a3e",
        media_type: "image",
        title: "Mobile Surface — Mobile Portfolio Companion",
        url: getLocalPublicUrl("orbit-finance", "mobile.webp"),
        thumbnail_url: getLocalPublicUrl("orbit-finance", "mobile.webp"),
        provider: "Snow Media Library",
        alt_text: "Orbit Finance mobile view concept screenshot",
        sort_order: 3,
      },
    ],
  },
  {
    id: "04f05a53-4768-4326-b46b-d3c5ef219a3f",
    slug: "nova-ai-assistant",
    title: "Nova AI Assistant",
    client_name: "AI Workflow Exploration",
    project_type_label: "Engineering Concept",
    composition_variant: "split-perspective",
    related_service_slug: "ai-solutions-automation",
    category: "AI & Intelligence",
    summary: "A spatial conversational workspace concept with dynamic context management and streaming AI interface layouts.",
    description:
      "Nova AI is an engineering exploration into conversational interface design, streaming token state management, and dynamic prompt context visualization.",
    problem: "Traditional AI chat interfaces lack structural organization for long-form context and multi-agent workflows.",
    solution: "A spatial workspace layout concept separating context memory, dynamic tool execution logs, and streaming output streams.",
    results: "Engineering concept exploring streaming latency optimization and context window visualization.",
    technologies: ["Next.js", "OpenAI API", "TypeScript", "Tailwind CSS", "Framer Motion"],
    featured: true,
    live_url: null,
    github_url: null,
    year: 2026,
    sort_order: 4,
    media: [
      {
        id: "nova-hero-1",
        project_id: "04f05a53-4768-4326-b46b-d3c5ef219a3f",
        media_type: "image",
        title: "Hero View — Conversational Intelligence Workspace",
        url: getLocalPublicUrl("nova-ai-assistant", "hero.webp"),
        thumbnail_url: getLocalPublicUrl("nova-ai-assistant", "hero.webp"),
        provider: "Snow Media Library",
        alt_text: "Nova AI Assistant hero interface concept preview",
        sort_order: 1,
      },
      {
        id: "nova-desk-2",
        project_id: "04f05a53-4768-4326-b46b-d3c5ef219a3f",
        media_type: "image",
        title: "Desktop Surface — Context & Prompt Inspector",
        url: getLocalPublicUrl("nova-ai-assistant", "desktop.webp"),
        thumbnail_url: getLocalPublicUrl("nova-ai-assistant", "desktop.webp"),
        provider: "Snow Media Library",
        alt_text: "Nova AI Assistant desktop interface concept preview",
        sort_order: 2,
      },
      {
        id: "nova-mob-3",
        project_id: "04f05a53-4768-4326-b46b-d3c5ef219a3f",
        media_type: "image",
        title: "Mobile Surface — Mobile Assistant Stream",
        url: getLocalPublicUrl("nova-ai-assistant", "mobile.webp"),
        thumbnail_url: getLocalPublicUrl("nova-ai-assistant", "mobile.webp"),
        provider: "Snow Media Library",
        alt_text: "Nova AI Assistant mobile interface concept preview",
        sort_order: 3,
      },
    ],
  },
  {
    id: "05f05a53-4768-4326-b46b-d3c5ef219a40",
    slug: "atlas-business-portal",
    title: "Atlas Business Portal",
    client_name: "Enterprise Workspace Concept",
    project_type_label: "Platform Prototype",
    composition_variant: "editorial",
    related_service_slug: "cloud-api-integrations",
    category: "Enterprise Portal",
    summary: "An enterprise control panel concept integrating identity, operational telemetry, and RBAC interface layouts.",
    description:
      "Atlas is an enterprise portal prototype exploring administrative dashboard concepts, role-based access control layouts, and audit log interfaces.",
    problem: "Fragmented tool stacks lead to lost operational visibility and security compliance risks.",
    solution: "A unified portal prototype with role-based access control (RBAC) layouts and audit log interfaces.",
    results: "Platform prototype demonstrating consolidation of multi-tool workflows into a unified role-based interface.",
    technologies: ["Next.js", "React", "Auth0", "Tailwind CSS", "GraphQL"],
    featured: false,
    live_url: null,
    github_url: null,
    year: 2026,
    sort_order: 5,
    media: [
      {
        id: "atlas-hero-1",
        project_id: "05f05a53-4768-4326-b46b-d3c5ef219a40",
        media_type: "image",
        title: "Hero View — Enterprise Control Center",
        url: getLocalPublicUrl("atlas-business-portal", "hero.webp"),
        thumbnail_url: getLocalPublicUrl("atlas-business-portal", "hero.webp"),
        provider: "Snow Media Library",
        alt_text: "Atlas Business Portal enterprise workspace view concept",
        sort_order: 1,
      },
      {
        id: "atlas-desk-2",
        project_id: "05f05a53-4768-4326-b46b-d3c5ef219a40",
        media_type: "image",
        title: "Desktop Surface — Operational Telemetry",
        url: getLocalPublicUrl("atlas-business-portal", "desktop.webp"),
        thumbnail_url: getLocalPublicUrl("atlas-business-portal", "desktop.webp"),
        provider: "Snow Media Library",
        alt_text: "Atlas Business Portal desktop dashboard concept",
        sort_order: 2,
      },
      {
        id: "atlas-mob-3",
        project_id: "05f05a53-4768-4326-b46b-d3c5ef219a40",
        media_type: "image",
        title: "Mobile Surface — Executive Mobile App",
        url: getLocalPublicUrl("atlas-business-portal", "mobile.webp"),
        thumbnail_url: getLocalPublicUrl("atlas-business-portal", "mobile.webp"),
        provider: "Snow Media Library",
        alt_text: "Atlas Business Portal mobile view concept",
        sort_order: 3,
      },
    ],
  },
  {
    id: "06f05a53-4768-4326-b46b-d3c5ef219a41",
    slug: "studio-landing",
    title: "Studio Landing",
    client_name: "Spatial Design Exploration",
    project_type_label: "Design Exploration",
    composition_variant: "minimal",
    related_service_slug: "ui-ux-design",
    category: "Design & Spatial",
    summary: "Immersive brand showcase concept with 3D perspective depth and fluid architectural layout presentation.",
    description:
      "A digital presence design exploration featuring spatial 3D perspective depth, fluid typography, and dynamic project filtering concepts.",
    problem: "Architectural agencies need site experiences that reflect physical spatial quality and premium craftsmanship.",
    solution: "Spatial perspective animations, 3D tilt effects, and responsive asset layout concepts.",
    results: "Design exploration combining 3D perspective depth with responsive layout presentation.",
    technologies: ["Next.js", "Framer Motion", "Tailwind CSS", "TypeScript"],
    featured: false,
    live_url: null,
    github_url: null,
    year: 2026,
    sort_order: 6,
    media: [
      {
        id: "studio-hero-1",
        project_id: "06f05a53-4768-4326-b46b-d3c5ef219a41",
        media_type: "image",
        title: "Hero View — Spatial Architectural Showcase",
        url: getLocalPublicUrl("studio-landing", "hero.webp"),
        thumbnail_url: getLocalPublicUrl("studio-landing", "hero.webp"),
        provider: "Snow Media Library",
        alt_text: "Studio Landing architectural design hero view concept",
        sort_order: 1,
      },
      {
        id: "studio-desk-2",
        project_id: "06f05a53-4768-4326-b46b-d3c5ef219a41",
        media_type: "image",
        title: "Desktop Surface — Portfolio Gallery",
        url: getLocalPublicUrl("studio-landing", "desktop.webp"),
        thumbnail_url: getLocalPublicUrl("studio-landing", "desktop.webp"),
        provider: "Snow Media Library",
        alt_text: "Studio Landing desktop concept screenshot",
        sort_order: 2,
      },
      {
        id: "studio-mob-3",
        project_id: "06f05a53-4768-4326-b46b-d3c5ef219a41",
        media_type: "image",
        title: "Mobile Surface — Mobile Gallery View",
        url: getLocalPublicUrl("studio-landing", "mobile.webp"),
        thumbnail_url: getLocalPublicUrl("studio-landing", "mobile.webp"),
        provider: "Snow Media Library",
        alt_text: "Studio Landing mobile view concept",
        sort_order: 3,
      },
    ],
  },
  {
    id: "07f05a53-4768-4326-b46b-d3c5ef219a42",
    slug: "local-services-platform",
    title: "Local Services Platform",
    client_name: "Urban Mobility Prototype",
    project_type_label: "Product Exploration",
    composition_variant: "device-stack",
    related_service_slug: "custom-software-web-apps",
    category: "Mobile App",
    summary: "An offline-first local service marketplace concept exploring location-based filtering and booking interfaces.",
    description:
      "A product exploration studying map navigation interfaces, notification dispatch concepts, and provider verification UI workflows for local service platforms.",
    problem: "Local service booking platforms are often bloated, slow on mobile networks, and hard to navigate.",
    solution: "An offline-first Progressive Web App (PWA) concept with location-based filtering and instant booking flows.",
    results: "Product exploration for offline-first progressive web application navigation concepts.",
    technologies: ["React", "PWA", "Mapbox", "Node.js", "Tailwind CSS"],
    featured: false,
    live_url: null,
    github_url: null,
    year: 2026,
    sort_order: 7,
    media: [
      {
        id: "local-hero-1",
        project_id: "07f05a53-4768-4326-b46b-d3c5ef219a42",
        media_type: "image",
        title: "Hero View — City Navigation & Mapping",
        url: getLocalPublicUrl("local-services-platform", "hero.webp"),
        thumbnail_url: getLocalPublicUrl("local-services-platform", "hero.webp"),
        provider: "Snow Media Library",
        alt_text: "Local Services Platform mapping hero view concept",
        sort_order: 1,
      },
      {
        id: "local-desk-2",
        project_id: "07f05a53-4768-4326-b46b-d3c5ef219a42",
        media_type: "image",
        title: "Desktop Surface — Provider Marketplace",
        url: getLocalPublicUrl("local-services-platform", "desktop.webp"),
        thumbnail_url: getLocalPublicUrl("local-services-platform", "desktop.webp"),
        provider: "Snow Media Library",
        alt_text: "Local Services Platform desktop map view concept",
        sort_order: 2,
      },
      {
        id: "local-mob-3",
        project_id: "07f05a53-4768-4326-b46b-d3c5ef219a42",
        media_type: "image",
        title: "Mobile Surface — Mobile PWA App",
        url: getLocalPublicUrl("local-services-platform", "mobile.webp"),
        thumbnail_url: getLocalPublicUrl("local-services-platform", "mobile.webp"),
        provider: "Snow Media Library",
        alt_text: "Local Services Platform mobile view concept",
        sort_order: 3,
      },
    ],
  },
  {
    id: "08f05a53-4768-4326-b46b-d3c5ef219a43",
    slug: "secure-account-recovery",
    title: "Secure Account Recovery",
    client_name: "Cyber Assurance Study",
    project_type_label: "Engineering Concept",
    composition_variant: "dark-lab",
    related_service_slug: "cybersecurity-digital-safety",
    category: "Security",
    summary: "An engineering concept for security audit dashboards and guided recovery interfaces for business accounts.",
    description:
      "Incident triage UI, security header auditing views, vulnerability assessment layouts, and recovery planning workflows for digital account safety.",
    problem: "Account owners facing security incidents need fast, verified guidance and defensive hardening without falling for scams.",
    solution: "Audit log interfaces, multi-factor authentication enforcement layouts, and zero-trust verification pipeline concepts.",
    results: "Engineering concept for zero-trust verification flows and audit log UI concepts.",
    technologies: ["Next.js", "Security Headers", "JWT", "TypeScript", "Cyber Triage"],
    featured: false,
    live_url: null,
    github_url: null,
    year: 2026,
    sort_order: 8,
    media: [
      {
        id: "sec-hero-1",
        project_id: "08f05a53-4768-4326-b46b-d3c5ef219a43",
        media_type: "image",
        title: "Hero View — Defensive Security Shield",
        url: getLocalPublicUrl("secure-account-recovery", "hero.webp"),
        thumbnail_url: getLocalPublicUrl("secure-account-recovery", "hero.webp"),
        provider: "Snow Media Library",
        alt_text: "Secure Account Recovery security shield view concept",
        sort_order: 1,
      },
      {
        id: "sec-desk-2",
        project_id: "08f05a53-4768-4326-b46b-d3c5ef219a43",
        media_type: "image",
        title: "Desktop Surface — Hardened Security Terminal",
        url: getLocalPublicUrl("secure-account-recovery", "desktop.webp"),
        thumbnail_url: getLocalPublicUrl("secure-account-recovery", "desktop.webp"),
        provider: "Snow Media Library",
        alt_text: "Secure Account Recovery desktop terminal concept",
        sort_order: 2,
      },
      {
        id: "sec-mob-3",
        project_id: "08f05a53-4768-4326-b46b-d3c5ef219a43",
        media_type: "image",
        title: "Mobile Surface — Mobile MFA & Verification",
        url: getLocalPublicUrl("secure-account-recovery", "mobile.webp"),
        thumbnail_url: getLocalPublicUrl("secure-account-recovery", "mobile.webp"),
        provider: "Snow Media Library",
        alt_text: "Secure Account Recovery mobile verification preview concept",
        sort_order: 3,
      },
    ],
  },
];

function enrichProject(project: ProjectWithMedia): ProjectWithMedia {
  const mediaList = project.media || [];
  const hero = mediaList.find((m) => m.sort_order === 1) || mediaList[0];
  const desktop = mediaList.find((m) => m.sort_order === 2) || mediaList[1] || hero;
  const mobile = mediaList.find((m) => m.sort_order === 3) || mediaList[2] || hero;

  return {
    ...project,
    hero_media: hero,
    desktop_media: desktop,
    mobile_media: mobile,
    screenshots: mediaList.filter((m) => m.id !== hero?.id),
  };
}

export async function fetchProjects(): Promise<ProjectWithMedia[]> {
  return STATIC_PROJECTS.map(enrichProject);
}

export async function fetchProjectBySlug(slug: string): Promise<ProjectWithMedia | null> {
  const projects = await fetchProjects();
  const project = projects.find((p) => p.slug === slug);
  return project || null;
}
