import Link from "next/link";
import Image from "next/image";
import { getFeaturedProjects, getFaqs, getServices } from "@/lib/data";

export const dynamic = "force-dynamic";

export default async function Home() {
  const [services, projects, faqs] = await Promise.all([getServices(), getFeaturedProjects(), getFaqs()]);
  return <main>
    <header className="site-header"><Link href="/" className="logo" aria-label="Snow home"><span className="logo-mark">✦</span> Snow</Link><nav className="nav-links" aria-label="Main navigation"><Link href="/services">Services</Link><Link href="/work">Work</Link><Link href="/about">About</Link><Link href="/faq">FAQ</Link></nav><Link href="/contact" className="header-cta">Start a project <span>↗</span></Link></header>
    <section className="hero section-pad"><div className="hero-copy"><p className="eyebrow">Technology made clearer.</p><h1>Technology problems?<br/><em>Let&apos;s build the solution.</em></h1><p className="hero-lede">Snow builds, fixes, improves and automates the websites, apps and digital systems that move your work forward.</p><div className="hero-actions"><Link href="/contact" className="button button-dark">Start a project <span>↗</span></Link><Link href="/work" className="text-link">Explore our work <span>→</span></Link></div></div><div className="hero-visual" aria-label="Snow systems visualization"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="hero-core"><span>✦</span><small>SNOW / SYSTEMS</small></div><div className="signal signal-a">BUILD <b>↗</b></div><div className="signal signal-b">AI <b>↗</b></div><div className="signal signal-c">GROW <b>↗</b></div></div></section>
    <section className="ticker"><div>BUILD <span>✦</span> FIX <span>✦</span> CONNECT <span>✦</span> PROTECT <span>✦</span> GROW <span>✦</span> BUILD</div></section>
    <section className="section-pad dark-section"><div className="section-intro"><p className="eyebrow light">What Snow does</p><h2>From first idea<br/>to <em>better system.</em></h2><p>One capable partner for the parts of technology that are exciting, frustrating or still unclear.</p></div><div className="service-grid">{services.length ? services.slice(0, 9).map((service, index) => <Link href={`/services/${service.slug}`} className="service-card" key={service.id}><span className="service-number">{String(index + 1).padStart(2, "0")}</span><h3>{service.name ?? service.title}</h3><p>{service.short_description ?? service.description}</p><span className="service-arrow">↗</span></Link>) : <p className="empty-note">Services are being prepared.</p>}</div></section>
    <section className="section-pad work-section"><div className="section-intro split"><div><p className="eyebrow">Selected work</p><h2>Useful, not<br/><em>just beautiful.</em></h2><p>Explore selected Snow concept builds and digital experiments.</p></div><Link href="/work" className="text-link">Explore all work <span>→</span></Link></div><div className="work-grid">{projects.map(project => <Link href={`/work/${project.slug}`} className="work-card" key={project.id}><span>CONCEPT DEMO</span>{project.project_media?.[0] && <Image src={project.project_media[0].url} alt={project.project_media[0].alt_text ?? project.title} width={1200} height={760} sizes="(max-width: 700px) 88vw, 42vw" className="work-image"/>}<div><h3>{project.title}</h3><p>{project.short_description ?? project.description}</p></div></Link>)}</div></section>
    <section className="section-pad faq-section"><div className="section-intro split"><div><p className="eyebrow">Frequently asked</p><h2>Clear answers<br/><em>first.</em></h2></div><Link href="/faq" className="text-link">See all FAQs <span>→</span></Link></div><div className="faq-list">{(faqs.length ? faqs.slice(0, 4) : [{ id: "fallback", question: "What kind of projects does Snow take on?", answer: "Snow works across websites, web apps, mobile products and connected systems." }]).map(faq => <details className="faq-item" key={faq.id}><summary>{faq.question}<b>+</b></summary><p>{faq.answer}</p></details>)}</div></section>
    <section className="contact-band"><p className="eyebrow light">Have a problem to solve?</p><h2>Let&apos;s make technology<br/><em>feel simpler.</em></h2><Link href="/contact" className="button button-light">Start a project <span>↗</span></Link></section><footer className="footer"><Link href="/" className="logo"><span className="logo-mark">✦</span> Snow</Link><p>Technology made clearer.</p><div><Link href="/services">Services</Link><Link href="/work">Work</Link><Link href="/contact">Contact</Link></div><small>© 2026 Snow. Built for better systems.</small></footer>
  </main>;
}
