import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { getFaqs, getFeaturedProjects, getProject, getProjects, getService, getServices } from "@/lib/data";

export const dynamic = "force-dynamic";

export default async function RoutePage({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params; const [section, value] = slug;
  if (section === "work" && value) { const project = await getProject(value); if (!project) notFound(); return <main><SimpleHeader/><article className="detail-page"><p className="eyebrow">Snow / Work / Concept Demo</p><div className="detail-heading"><div><span className="concept-badge">CONCEPT DEMO</span><h1>{project.title}<br/><em>designed to demonstrate.</em></h1></div><p className="hero-lede">{project.description}</p></div><div className="detail-hero">{project.project_media?.[0] && <Image src={project.project_media[0].url} alt={project.project_media[0].alt_text ?? project.title} width={1200} height={760} priority sizes="(max-width: 700px) 88vw, 82vw"/>}</div><div className="media-gallery" aria-label={`${project.title} concept media`}>{(project.project_media ?? []).slice(1).map(media => <figure key={media.id}><Image src={media.url} alt={media.alt_text ?? media.title} width={900} height={560} sizes="(max-width: 700px) 88vw, 40vw"/><figcaption>{media.title} · {media.media_type}</figcaption></figure>)}</div><div className="detail-grid"><Info title="The brief" text={project.problem ?? "A focused concept exploration for a clearer digital experience."}/><Info title="The approach" text={project.solution ?? "A considered interface system shaped around useful interactions and calm information hierarchy."}/><Info title="Technology demonstrated" text={Array.isArray(project.technologies) ? project.technologies.join(" · ") : project.technologies ?? "Web design · Responsive UI · Product thinking"}/></div><div className="detail-copy"><h2>Concept features</h2><p>{project.short_description ?? project.description}</p><p className="muted">{project.results ?? "Concept demonstration — not a client project."}</p></div><Link href="/contact" className="button button-dark">Build something similar <span>↗</span></Link></article></main>; }
  if (section === "services" && value) { const service = await getService(value); if (!service) notFound(); return <main><SimpleHeader/><article className="detail-page service-detail"><p className="eyebrow">Snow / Services</p><h1>{service.name ?? service.title}<br/><em>made clearer.</em></h1><p className="hero-lede">{service.description ?? service.short_description ?? "A thoughtful, practical technology service shaped around your goals."}</p><div className="detail-copy"><h2>What this can include</h2><p>We start with the problem, make the next step clear, and build a system that is useful, maintainable and ready to evolve.</p></div><Link href="/contact" className="button button-dark">Talk to Snow <span>↗</span></Link></article></main>; }
  if (section === "demos") { const projects = await getFeaturedProjects(); return <main><SimpleHeader/><article className="listing-page"><p className="eyebrow">Snow / Demo Showcase</p><h1>Ideas you can<br/><em>see working.</em></h1><p className="hero-lede">Interactive concept directions built to make possibilities tangible. Every item here is a prototype, not a client product.</p><div className="work-grid">{projects.map(project => <Link href={`/work/${project.slug}`} className="work-card" key={project.id}><span>INTERACTIVE CONCEPT</span>{project.project_media?.[0] && <Image src={project.project_media[0].url} alt={project.project_media[0].alt_text ?? project.title} width={1200} height={760} sizes="(max-width: 700px) 88vw, 42vw" className="work-image"/>}<div><h3>{project.title}</h3><p>{project.short_description ?? project.description}</p></div></Link>)}</div></article></main>; }
  if (section === "work") { const projects = await getProjects(); return <main><SimpleHeader/><article className="listing-page"><p className="eyebrow">Snow / Work</p><h1>Selected concept<br/><em>builds.</em></h1><p className="hero-lede">Explore selected Snow concept builds and digital experiments.</p><div className="work-grid">{projects.map(project => <Link href={`/work/${project.slug}`} className="work-card" key={project.id}><span>CONCEPT DEMO</span><div><h3>{project.title}</h3><p>{project.short_description ?? project.description}</p></div></Link>)}</div></article></main>; }
  if (section === "services") { const services = await getServices(); return <main><SimpleHeader/><article className="listing-page"><p className="eyebrow">Snow / Services</p><h1>Technology<br/><em>made clearer.</em></h1><div className="service-list">{services.map(s => <Link href={`/services/${s.slug}`} key={s.id}><span>{s.name ?? s.title}</span><b>↗</b></Link>)}</div></article></main>; }
  if (section === "faq") { const faqs = await getFaqs(); return <main><SimpleHeader/><article className="listing-page"><p className="eyebrow">Snow / FAQ</p><h1>Clear answers<br/><em>first.</em></h1><div className="faq-list">{faqs.map(faq => <details className="faq-item" key={faq.id}><summary>{faq.question}<b>+</b></summary><p>{faq.answer}</p></details>)}</div></article></main>; }
  return <main><SimpleHeader/><article className="listing-page"><p className="eyebrow">Snow / Contact</p><h1>Let&apos;s make technology<br/><em>feel simpler.</em></h1><p className="hero-lede">Tell us what you are building, fixing or figuring out. We&apos;ll make the next step clear.</p><Link href="mailto:hello@snow.studio" className="button button-dark">hello@snow.studio <span>↗</span></Link></article></main>;
}
function SimpleHeader() { return <header className="site-header"><Link href="/" className="logo"><span className="logo-mark">✦</span> Snow</Link><nav className="nav-links"><Link href="/services">Services</Link><Link href="/work">Work</Link><Link href="/faq">FAQ</Link></nav><Link href="/contact" className="header-cta">Start a project <span>↗</span></Link></header>; }
function Info({ title, text }: { title: string; text: string }) { return <div><p className="eyebrow">{title}</p><p>{text}</p></div>; }
