"use client";
import { useMemo, useState } from "react";
import { OPERATION_META, type SecurityMode, type SecurityOperation, type SecuritySimulationState } from "@/lib/security/simulation";
type Props={state:SecuritySimulationState;onSelect:(operation:SecurityOperation)=>void;onMode:(mode:SecurityMode)=>void;onAction:(action:string,value?:string)=>void};
const Button=({children,onClick,active=false}:{children:React.ReactNode;onClick:()=>void;active?:boolean})=><button type="button" onClick={onClick} className={`security-command-button ${active?"is-active":""}`}>{children}</button>;
const Readout=({label,value}:{label:string;value:React.ReactNode})=><div className="security-readout"><span>{label}</span><strong>{value}</strong></div>;
const Header=({title,status}:{title:string;status:string})=><div className="security-panel-heading"><span>{title}</span><span className="text-cyan-300">{status}</span></div>;
export function SecurityOperationPanel({state,onSelect,onMode,onAction}:Props){
 const [filter,setFilter]=useState("ALL"); const [webTab,setWebTab]=useState("SQL INJECTION"); const [defenses,setDefenses]=useState({CSP:true,HSTS:true,"X-FRAME-OPTIONS":false}); const [exploitCommand,setExploitCommand]=useState("show options");
 const packets=useMemo(()=>filter==="ALL"?state.packets:state.packets.filter(p=>p.protocol===filter),[filter,state.packets]); const discovered=state.hosts.filter(h=>h.discovered).length; const complete=state.mission.stages.filter(s=>s.status==="complete").length;
 return <section id="operations" className="security-operations" aria-labelledby="operations-title"><div className="mb-4 flex flex-wrap items-end justify-between gap-4"><div><p className="security-kicker">01 / CONTROL DECK</p><h2 id="operations-title" className="security-section-title">OPERATIONS</h2></div><div className="security-mode-switch" role="group" aria-label="Team mode"><button type="button" onClick={()=>onMode("red")} className={state.mode==="red"?"is-active":""}>RED TEAM</button><button type="button" onClick={()=>onMode("blue")} className={state.mode==="blue"?"is-active":""}>BLUE TEAM</button></div></div>
 <div className="security-operation-groups">{["LIVE SIMULATION","DEFENSIVE SIMULATION","MISSION"].map(group=><div key={group}><p className="security-kicker mb-2">{group}</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{OPERATION_META.filter(m=>m.group===group).map(meta=><button key={meta.id} type="button" onClick={()=>onSelect(meta.id)} className={`security-operation-tab ${state.operation===meta.id?"is-active":""}`}><span>{meta.number}</span><strong>{meta.label}</strong><small>{meta.description}</small></button>)}</div></div>)}</div>
 <div className="mt-4 security-panel min-h-[310px]">
 {state.operation==="recon"&&<div id="recon"><Header title="RECON // SNOWMAP-SIM / NMAP-STYLE LAB" status={state.scanProgress>=100?"COMPLETE":`${state.scanProgress}% SCANNING`}/><div className="grid gap-3 sm:grid-cols-4"><Readout label="TARGET" value="10.42.0.0/24"/><Readout label="HOSTS" value={`${discovered} / 7 discovered`}/><Readout label="MODE" value="FULL + SERVICE"/><Readout label="CONFIDENCE" value="94%"/></div><div className="security-meter mt-5"><span style={{width:`${state.scanProgress}%`}}/></div><div className="mt-5 grid gap-2 font-mono text-xs text-slate-300 sm:grid-cols-2">{state.hosts.map(host=><div key={host.id} className="flex items-center justify-between border-b border-emerald-400/10 py-2"><span>{host.address} / {host.hostname}</span><span className={host.discovered?"text-emerald-300":"text-slate-600"}>{host.discovered?host.status.toUpperCase():"UNDISCOVERED"}</span></div>)}</div><Button onClick={()=>onAction("recon")}>RUN FULL SCAN →</Button></div>}
 {state.operation==="credentials"&&<div id="credentials"><Header title="HASHCORE-SIM // CREDENTIAL LAB" status={state.credentials.some(c=>c.discovered)?"MATCH FOUND":"READY"}/><div className="grid gap-3 sm:grid-cols-4"><Readout label="TARGET" value="AUTH-01"/><Readout label="HASH" value={state.credentials[0].hashType}/><Readout label="CANDIDATES" value="48,192"/><Readout label="RATE" value="18,420/s"/></div><div className="security-meter mt-5"><span style={{width:state.credentials[0].discovered?"100%":"71.4%"}}/></div><div className="mt-5 flex flex-wrap gap-2">{["DICTIONARY","BRUTE FORCE","MASK","RULE-BASED","HYBRID","CREDENTIAL REUSE"].map(s=><Button key={s} onClick={()=>onAction("credentials",s)}>{s}</Button>)}</div><p className="mt-4 font-mono text-xs text-slate-400">{state.credentials[0].discovered?"MATCH FOUND // snow-lab-demo — fictional fixture only":"Select a simulation strategy. Real credentials are never accepted."}</p></div>}
 {state.operation==="auth"&&<div><Header title="AUTHSTREAM-SIM // MEDUSA / HYDRA-STYLE LAB" status="IDS STANDBY"/><div className="grid gap-3 sm:grid-cols-5"><Readout label="TARGET" value="AUTH-01"/><Readout label="PROTOCOL" value="SSH"/><Readout label="USER SET" value="admin · operator · snow"/><Readout label="THREADS" value="8"/><Readout label="ATTEMPTS" value="124 / 640"/></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{["SSH","HTTP LOGIN","API AUTH","FICTIONAL DB"].map(p=><Button key={p} onClick={()=>onAction("auth",p)}>{p} → SIMULATE</Button>)}</div><p className="mt-4 font-mono text-xs text-amber-300">{state.alerts.some(a=>a.type==="AUTH FAILURE")?"IDS ALERT // RATE LIMIT + ACCOUNT LOCK SIMULATED":"Detection is connected to the Blue Team response loop."}</p></div>}
 {state.operation==="packets"&&<div><Header title="PACKET LAB // SYNTHETIC SENSOR 01" status={`${packets.length} FRAMES`}/><div className="mb-3 flex gap-2 overflow-x-auto pb-1">{["ALL","TCP","TLS","HTTP","DNS","SSH"].map(item=><button key={item} type="button" onClick={()=>setFilter(item)} className={`security-filter ${filter===item?"is-active":""}`}>{item}</button>)}</div><div className="overflow-x-auto"><table className="security-packet-table"><thead><tr><th>TIME</th><th>SOURCE</th><th>DESTINATION</th><th>PROTO</th><th>LENGTH</th><th>INFO</th></tr></thead><tbody>{packets.map(packet=><tr key={packet.id} className={packet.suspicious?"is-suspicious":""}><td>{packet.timestamp}</td><td>{packet.source}</td><td>{packet.destination}</td><td className="text-cyan-300">{packet.protocol}</td><td>{packet.length}</td><td>{packet.info}</td></tr>)}</tbody></table></div><div className="mt-4 grid gap-2 sm:grid-cols-5">{["FRAME","ETHERNET","IP","TCP","APPLICATION"].map(layer=><span key={layer} className="security-layer">{layer}</span>)}</div><p className="mt-4 font-mono text-[11px] text-slate-400">Synthetic display filters operate on Snow&apos;s local dataset only. No capture device is accessed.</p></div>}
 {state.operation==="web"&&<div><Header title="SNOWLAB-WEB-01 // WEB SECURITY SANDBOX" status="CONTROLLED TARGET"/><div className="mb-4 flex flex-wrap gap-2">{["SQL INJECTION","XSS","AUTHENTICATION","HEADERS"].map(tab=><Button key={tab} active={webTab===tab} onClick={()=>setWebTab(tab)}>{tab}</Button>)}</div>{webTab==="SQL INJECTION"&&<div className="grid gap-3 sm:grid-cols-4"><Readout label="INPUT" value="username=demo"/><Readout label="QUERY" value="SELECT fixture"/><Readout label="DATABASE" value="SNOWLAB_DB"/><Readout label="DETECTION" value="MATCHED"/></div>}{webTab==="XSS"&&<div className="grid gap-3 sm:grid-cols-4"><Readout label="INPUT" value="safe fixture"/><Readout label="SANITIZER" value="CSP + ENCODE"/><Readout label="RENDER" value="REFLECTED"/><Readout label="RESULT" value="CONTAINED"/></div>}{webTab==="AUTHENTICATION"&&<div className="grid gap-3 sm:grid-cols-3"><Readout label="SESSION" value="FIXATION DEMO"/><Readout label="TOKEN" value="FICTIONAL JWT"/><Readout label="RESULT" value="ROTATION ADVISED"/></div>}{webTab==="HEADERS"&&<div className="grid gap-2 sm:grid-cols-2">{Object.entries(defenses).map(([key,enabled])=><button key={key} type="button" className="security-readout text-left" onClick={()=>setDefenses(current=>({...current,[key]:!enabled}))}><span>{key}</span><strong className={enabled?"text-emerald-300":"text-red-300"}>{enabled?"ENABLED":"SIMULATED GAP"}</strong></button>)}</div>}<p className="mt-4 font-mono text-xs text-slate-400">Every request follows INPUT → CONTROLLED FIXTURE → RESPONSE → DETECTION. No external requests are sent.</p></div>}
 {state.operation==="exploit"&&<div><Header title="SNOWPLOIT // SIMULATED EXPLOIT CONSOLE" status="NO SHELL ACCESS"/><div className="security-console-output">snowploit &gt; {exploitCommand}<br/><span className="text-emerald-300">{exploitCommand==="exploit"?"[+] Session established / simulated state object created":exploitCommand==="check"?"[+] TARGET VULNERABLE (SIMULATION)":"TARGET web-01 · PORT 443 · PAYLOAD reverse-session-sim"}</span></div><div className="mt-4 flex flex-wrap gap-2">{["search web","use exploit/web/demo-auth-bypass","show options","set target web-01","check","exploit","sessions","background"].map(command=><Button key={command} onClick={()=>{setExploitCommand(command);onAction("exploit",command)}}>{command}</Button>)}</div><p className="mt-4 font-mono text-xs text-amber-300">Simulation only. No payload execution, command shell, or real target selection is possible.</p></div>}
 {state.operation==="defense"&&<div id="defense"><Header title="BLUE TEAM // FIREWALL CONTROL" status="CONNECTED TO IDS"/><div className="grid gap-3 sm:grid-cols-4"><Readout label="ALERTS" value={state.alerts.filter(a=>!a.resolved).length}/><Readout label="BLOCKED HOSTS" value={state.defense.blockedHosts.length}/><Readout label="ISOLATED" value={state.defense.isolatedHosts.length}/><Readout label="SESSIONS" value={state.sessions.length}/></div><div className="mt-5 grid gap-2 sm:grid-cols-3"><Button onClick={()=>onAction("block","10.42.0.27")}>BLOCK IP</Button><Button onClick={()=>onAction("isolate","auth-01")}>ISOLATE HOST</Button><Button onClick={()=>onAction("rate-limit","AUTH-01")}>ENABLE RATE LIMIT</Button><Button onClick={()=>onAction("lock","snow")}>LOCK ACCOUNT</Button><Button onClick={()=>onAction("reset","all")}>RESET SESSION</Button><Button onClick={()=>onAction("quarantine","SSH")}>QUARANTINE SERVICE</Button></div></div>}
 {state.operation==="ids"&&<div><Header title="IDS // BLUE TEAM ALERT TRIAGE" status={state.alerts.length?"ALERTS ACTIVE":"WATCHING"}/>{state.alerts.length===0?<p className="py-10 text-center font-mono text-xs text-slate-500">No alerts yet. Run an attack simulation to generate a deterministic event.</p>:<div className="space-y-2">{state.alerts.map(alert=><div key={alert.id} className={`security-alert ${alert.resolved?"is-resolved":""}`}><div><strong>{alert.type}</strong><span>{alert.timestamp} · {alert.source} → {alert.target}</span><small>{alert.rule}</small></div><Button onClick={()=>onAction("resolve",alert.id)}>{alert.resolved?"RESOLVED":"ACK / CONTAIN"}</Button></div>)}</div>}</div>}
 {state.operation==="missions"&&<div id="missions"><Header title="BLACK ICE // MISSION CONTROL" status={`${complete} / ${state.mission.stages.length} COMPLETE`}/><div className="security-mission-progress"><span style={{width:`${(complete/state.mission.stages.length)*100}%`}}/></div><div className="mt-5 grid gap-2 font-mono text-xs text-slate-300">{state.mission.stages.map((stage,index)=><div key={stage.id} className="flex items-center gap-3 border-b border-emerald-400/10 py-2"><span className={stage.status==="complete"?"text-emerald-300":stage.status==="in-progress"?"text-cyan-300":"text-slate-600"}>{stage.status==="complete"?"✓":stage.status==="in-progress"?"→":"□"}</span><span>{String(index+1).padStart(2,"0")} / {stage.label}</span><span className="ml-auto text-[10px] uppercase text-slate-500">{stage.status}</span></div>)}</div>{complete>=state.mission.stages.length&&<p className="mt-5 font-mono text-sm text-emerald-300">FLAG // {state.mission.flag}</p>}<p className="mt-4 font-mono text-xs text-slate-400">Mission stages react to recon, discovery, access, detection, and defensive actions in the shared environment.</p></div>}
 </div></section>;
}
